### ISSUE TITLE
Question about Fig. 7

### ISSUE THREAD

**Issue by wjczf123** [Zk4-ps/EaaS-Embedding-Watermark#3]
Thanks for nice work.

I have two questions about Fig. 7. (1) What is the meaning of len($e_0$)? (2) Why is the watermark vector binary?

**Comment by Zk4-ps** [comment]
Well, for the first question: if the $e_o$ you mentioned is in the watermark embedding phase, it means the original embedding vector from the service provider without watermark. Then, for the second question: the watermark vector can be binary or float instead. However, the binary vector has the advantage that we can merge the values in the output vector to 0 or 1. For example, the value in the interval (0.5, 1) may be set to value 1. This can improve the verification accuracy of watermarks. The details can be found in our work "Your Fixed Watermark is Fragile: Towards Semantic-Aware Watermark for EaaS Copyright Protection"🤗.

**Comment by wjczf123** [comment]
Thanks for your reply. I'm still a little confused about the first question. 

For example, the dim of $e_o$ is 768. Is the value of len($e_o$) 768?

**Comment by Zk4-ps** [comment]
> Thanks for your reply. I'm still a little confused about the first question.
> 
> For example, the dim of e o is 768. Is the value of len( e o ) 768?

Sure, if the dim of $e_o$ is 768, len($e_o$) == 768. It's just like the Mean Squared Error(MSE).🤔

**Comment by wjczf123** [comment]
Thanks. I get it.
